[project]
name = "komorebi"
version = "1.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.17.0",
    "pyside6>=6.10.1",
    "python-vlc>=3.0.0",
    "psutil>=7.0.0",
]
